name: Buildozer APK Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Kivy ekibinin her şeyi içinde hazır ettiği resmi konteyneri çağırıyoruz
    container:
      image: ghcr.io/kivy/buildozer:master

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Buildozer
      run: |
        # Konteyner içinde güvenli klasör izni veriyoruz
        git config --global --add safe.directory '*'
        # Lisanslar zaten yüklü, doğrudan derlemeyi başlatıyoruz
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: FoxBrowser-APK
        path: bin/*.apk
        
